# © PixelmonMod 2012-2024
# For assistance visit https://pixelmonmod.com/wiki/Config

# Whether or not traders can be used multiple times. If disabled, traders will disappear after completing their trade offers.
traders-reusable: false
# The amount of moves a Move Tutor will have.
moves-per-tutor: 20
# If set to False, this will be based on the remaining inventory of the player.
limit-shop-keeper-stack-size: true
