# © PixelmonMod 2012-2024
# For assistance visit https://pixelmonmod.com/wiki/Config

# Whether or not the Pokérus is enabled. This blocks the growth, the spread and the spawning of the Pokérus.
enabled: true
# Pokérus spawn rate (1/x). (0 to disable)
spawn-rate: 12288.0
# Whether or not the player should be informed if their Pokémon got Pokérus.
inform-players: true
# Chance to spread the Pokérus to the near Pokémon after a battle. (1/x) (-1 to disable; 0 to keep always active)
spread-rate: 5
