# © PixelmonMod 2012-2024
# For assistance visit https://pixelmonmod.com/wiki/Config

# The amount of PokéDollars the player will have when joining a world for the first time
starting-balance: 0.0
# Whether Amulet Coin will award double PokéDollars when used.
allow-amulet-coin: true
# The multiplier for how many PokéDollars will be awarded by using Amulet Coin (2.0 = 2x Multiplier)
amulet-coin-multiplier: 2
